export enum QuestionResponseType {
    String = "string",
    Boolean = "boolean",
    Integer = "integer",
    Decimal = "decimal",
    Location = "location",
    Json = "json",
    OptionSelect = "optionSelect",
    OptionList = "optionList",
    DateTime = "dateTime",
    Time = "time",
    Path = "path",
    Timeline = "timeline",
    None = "none",
}