export enum QuestionResponseType {
    String = "String",
    Boolean = "Boolean",
    Integer = "Integer",
    Decimal = "Decimal",
    Location = "Location",
    Json = "Json",
    OptionSelect = "OptionSelect",
    OptionList = "OptionList",
    DateTime = "DateTime",
    Time = "Time",
    Path = "Path",
    Timeline = "Timeline",
    None = "None",
}